---
title: "Project 1"
author: "Eliada Deschamps, Jack Grinblatt, Jon Tao, Ketan Kshirsagar, Aksshath Soundarrarajan"
date: "3/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Model


### Import Data

```{r}

listings <- read.csv("ProjectA_Listings2013.csv")


```


### Clense Data
```{r}

listings$loan_status <- as.factor(listings$loan_status)
listings$prosper_rating <-as.factor(listings$prosper_rating)
listings$scorex <-as.factor(listings$scorex)
listings$income_range <-as.factor(listings$income_range)
listings$income_range_description <-as.factor(listings$income_range_description)
listings$employment_status_description <-as.factor(listings$employment_status_description)
listings$occupation <-as.factor(listings$occupation)
listings$borrower_state <-as.factor(listings$borrower_state)
listings$borrower_city <-as.factor(listings$borrower_city)
listings$loan_status_description <- as.factor(listings$loan_status_description)


str(listings)
summary(listings)

```


### Build Linear Regression Models 

```{r}

```


### Build Logistic Regression Models

```{r}

```


### Final Analysis

Given the data...