---
title: "Project 1"
author: "Eliada Deschamps, Jack Grinblatt, Jon Tao, Ketan Kshirsagar, Aksshath Soundarrarajan"
date: "3/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Data Model


### Import Data

```{r}

listings <- read.csv("ProjectA_Listings2013.csv")


```


### Clense Data
```{r}

listings$loan_status <- as.factor(listings$loan_status)
listings$prosper_rating <-as.factor(listings$prosper_rating)
listings$scorex <-as.factor(listings$scorex)
listings$income_range <-as.factor(listings$income_range)
listings$income_range_description <-as.factor(listings$income_range_description)
listings$employment_status_description <-as.factor(listings$employment_status_description)
listings$occupation <-as.factor(listings$occupation)
listings$borrower_state <-as.factor(listings$borrower_state)
listings$borrower_city <-as.factor(listings$borrower_city)
listings$loan_status_description <- as.factor(listings$loan_status_description)


str(listings)
summary(listings)

```


### Build Linear Regression Models 

#Model 1

```{r}
model1 <-lm(prosper_score ~ ., data = listings)

summary(model1)
```
# Model 2

```{r}
model2 <-lm(prosper_score ~ number_of_days + principal_balance + loan_status + amount_funded + listing_term + listing_monthly_payment + scorex + income_range + stated_monthly_income + employment_status_description + dti_wprosper_loan + months_employed + monthly_debt + lender_indicator + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + first_recorded_credit_line + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + bankcard_utilization + total_open_revolving_accounts + installment_balance + real_estate_balance + revolving_balance + real_estate_payment + revolving_available_percent + total_inquiries + total_trade_items + satisfactory_accounts + was_delinquent_derog + now_delinquent_derog + delinquencies_over30_days + delinquencies_over60_days + delinquencies_over90_days , data = listings)

summary(model2)
```

# Model 3

```{r}

```


### Build Logistic Regression Models

#Model 1

```{r}
lrmodel1 <-glm(prosper_score ~ ., data = listings)

summary(lrmodel1)
```

#Model 2

```{r}
lrmodel2 <-glm(prosper_score ~ number_of_days + principal_balance + loan_status + amount_funded + listing_term + listing_monthly_payment + scorex + income_range + stated_monthly_income + employment_status_description + dti_wprosper_loan + months_employed + monthly_debt + lender_indicator + current_delinquencies + delinquencies_last7_years + public_records_last10_years + public_records_last12_months + first_recorded_credit_line + credit_lines_last7_years + inquiries_last6_months + amount_delinquent + current_credit_lines + bankcard_utilization + total_open_revolving_accounts + installment_balance + real_estate_balance + revolving_balance + real_estate_payment + revolving_available_percent + total_inquiries + total_trade_items + satisfactory_accounts + was_delinquent_derog + now_delinquent_derog + delinquencies_over30_days + delinquencies_over60_days + delinquencies_over90_days, data = listings)

summary(lrmodel2)
```

#Model 3

```{r}

```


### Final Analysis

Given the data...
